### ISSUE TITLE
Externer Link - neues Fenster

### ISSUE THREAD

**Issue by rleugger** [aktion-hip/vgz-module#64]
Wenn ein externer Link angeklickt wird, sollte dieser ein neues Fenster öffnen. Bei internen Links ist dies nicht nötig (aber möglich)

**Comment by aktion-hip** [comment]
Das ist jetzt schon möglich.
Zu diesem Zweck musst du im WYSISYG-Editor des Textabschnitts mit Doppelklick die Link-Konfiguration öffnen. Du siehst dann ein Popup-Fenster mit den drei Tabs _Link Info_, _Target_ und _Advanced_. Auf dem Tab Target siehst du das Auswahlfeld _Target_, in welchem du den Eintrag **New Window (_blank)** wählen musst.
Wenn du den Link mit dieser Einstellung speicherst, wird in Zukunft das Ziel dieses Links in einem neuen Browser-Tab angezeigt.
Getestet habe ich das mit der Seite _Tai Ji_ (https://www.stadtoase.ch/stadtoase/bewegung/tai-ji.html).
