### ISSUE TITLE
Veranstaltung an effektivem Datum nicht auf Agenda

### ISSUE THREAD

**Issue by rleugger** [aktion-hip/vgz-module#66]
An dem Datum einer Veranstaltung wird diese nicht mehr auf der Agenda angezeigt, egal ob das Feld "Enddatum" leer oder gefüllt (mit gleichem Datum) ist.
![Bildschirmfoto 2022-06-23 um 18 34 19](https://user-images.githubusercontent.com/8500190/175352114-039c43a6-7d7d-4823-8e64-1ff6b229cf79.png)
![Bildschirmfoto 2022-06-23 um 18 34 39](https://user-images.githubusercontent.com/8500190/175352147-229027c0-3b18-4def-b014-ed224ead14f6.png)

**Comment by aktion-hip** [comment]
erledigt
