### ISSUE TITLE
Anfrage Seminarräume mittels Formular

### ISSUE THREAD

**Issue by rleugger** [aktion-hip/vgz-module#67]
Zur Zeit kommen alle Seminaranfragen per Mail. Für Katja wäre es effizienter, wenn wir einige Fragen schon mittels Formular standartisieren könnten.

Zeitraum (Datum von bis)
Uhrzeit (fakultativ)
Anzahl Personen (fakultativ)
welcher Raum (ToHo-Saal, SoPa-Saal, Dojo, Pavillon Ost)
Einrichtung gewünscht (Basic, Business, Lecture)
Pausenverpflegung
Mittagessen
Apéro

Klar hervorgehen sollte, das diese Offertanfrage unverbindlich ist.

**Comment by aktion-hip** [comment]
Liebe Rahel

Auf welcher Seite (URL) soll dieses Formular eingerichtet werden?

**Comment by rleugger** [comment]
https://www.stadtoase.ch/stadtoase/gesundheit/seminare-weiterbildungen0.html

**Comment by aktion-hip** [comment]
erledigt
