### ISSUE TITLE
Integration Friendly Analytics Tracking 

### ISSUE THREAD

**Issue by bsidedigital** [aktion-hip/vgz-module#83]
Code-Snippet bitte vor dem schliessenden </head>-Tag einbauen. (-> empfohlen)

<script>
  var _paq = window._paq = window._paq || [];
  /* tracker methods like "setCustomDimension" should be called before "trackPageView" */
  _paq.push(['trackPageView']);
  _paq.push(['enableLinkTracking']);
  (function() {
    var u="https://app.friendlyanalytics.ch/";
    _paq.push(['setTrackerUrl', u+'js/tracker.php']);
    _paq.push(['setSiteId', '283']);
    var d=document, g=d.createElement('script'), s=d.getElementsByTagName('script')[0];
    g.async=true; g.src=u+'js/tracker.php'; s.parentNode.insertBefore(g,s);
  })();
</script>

**Comment by aktion-hip** [comment]
Mit Release 1.1.1 umgesetzt.
